name: Inno Setup test

on:
  push

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # https://www.msys2.org/docs/ci/
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

    - uses: ./.github/actions/install-inno-setup

    - name: Build MyProg's installer
      run: |
        cd MyProg
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" Example1.iss
      shell: cmd

    - name: Install MyProg
      run: |
        START /WAIT MyProg\Output\mysetup.exe /VERYSILENT
      shell: cmd

    - name: Compile example with mingw
      run: |
        gcc -v
        cd examples/mingw
        mingw32-make.exe CC=gcc
      shell: msys2 {0}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MyProg/Output/mysetup.exe
