name: Inno Setup test

on:
  push

jobs:

  build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download Inno Setup
      run: |
        curl -L -o is.exe "https://jrsoftware.org/download.php/is.exe?site=2" && \
        ls -l && \
        sha1sum -c INNOSETUP_MANIFEST.txt
      shell: bash

    - name: Install Inno Setup
      run: |
       is.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES /DOWNLOADISCRYPT=1
      shell: cmd

    - name: Build MyProg's installer
      run: |
        cd MyProg
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" Example1.iss
      shell: cmd

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MyProg/Output/mysetup.exe
